// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: invoice.sql

package db

import (
	"context"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
`

func (q *Queries) CountInvoices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserInvoicesByID = `-- name: CountUserInvoicesByID :one
SELECT COUNT(*) FROM invoices
WHERE user_invoice_id = $1
`

func (q *Queries) CountUserInvoicesByID(ctx context.Context, userInvoiceID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countUserInvoicesByID, userInvoiceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    invoice_number, user_invoice_id, invoice_data, user_invoice_username, invoice_pdf
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING invoice_id, invoice_number, user_invoice_id, user_invoice_username, invoice_data, invoice_pdf, created_at
`

type CreateInvoiceParams struct {
	InvoiceNumber       string `json:"invoice_number"`
	UserInvoiceID       int32  `json:"user_invoice_id"`
	InvoiceData         []byte `json:"invoice_data"`
	UserInvoiceUsername string `json:"user_invoice_username"`
	InvoicePdf          []byte `json:"invoice_pdf"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.UserInvoiceID,
		arg.InvoiceData,
		arg.UserInvoiceUsername,
		arg.InvoicePdf,
	)
	var i Invoice
	err := row.Scan(
		&i.InvoiceID,
		&i.InvoiceNumber,
		&i.UserInvoiceID,
		&i.UserInvoiceUsername,
		&i.InvoiceData,
		&i.InvoicePdf,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT invoice_id, invoice_number, user_invoice_id, user_invoice_username, invoice_data, invoice_pdf, created_at FROM invoices
WHERE invoice_number = $1 
LIMIT 1
`

func (q *Queries) GetInvoice(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.InvoiceID,
		&i.InvoiceNumber,
		&i.UserInvoiceID,
		&i.UserInvoiceUsername,
		&i.InvoiceData,
		&i.InvoicePdf,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT invoice_id, invoice_number, user_invoice_id, user_invoice_username, invoice_data, invoice_pdf, created_at FROM invoices
WHERE invoice_id = $1 
LIMIT 1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, invoiceID int64) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, invoiceID)
	var i Invoice
	err := row.Scan(
		&i.InvoiceID,
		&i.InvoiceNumber,
		&i.UserInvoiceID,
		&i.UserInvoiceUsername,
		&i.InvoiceData,
		&i.InvoicePdf,
		&i.CreatedAt,
	)
	return i, err
}

const getUserInvoicesByID = `-- name: GetUserInvoicesByID :many
SELECT invoice_id, invoice_number, user_invoice_id, user_invoice_username, invoice_data, invoice_pdf, created_at FROM invoices
WHERE user_invoice_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetUserInvoicesByIDParams struct {
	UserInvoiceID int32 `json:"user_invoice_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

func (q *Queries) GetUserInvoicesByID(ctx context.Context, arg GetUserInvoicesByIDParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, getUserInvoicesByID, arg.UserInvoiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.InvoiceID,
			&i.InvoiceNumber,
			&i.UserInvoiceID,
			&i.UserInvoiceUsername,
			&i.InvoiceData,
			&i.InvoicePdf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInvoicesByUsername = `-- name: GetUserInvoicesByUsername :many
SELECT invoice_id, invoice_number, user_invoice_id, user_invoice_username, invoice_data, invoice_pdf, created_at FROM invoices
WHERE user_invoice_username = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserInvoicesByUsername(ctx context.Context, userInvoiceUsername string) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, getUserInvoicesByUsername, userInvoiceUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.InvoiceID,
			&i.InvoiceNumber,
			&i.UserInvoiceID,
			&i.UserInvoiceUsername,
			&i.InvoiceData,
			&i.InvoicePdf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT invoice_id, invoice_number, user_invoice_id, user_invoice_username, invoice_data, invoice_pdf, created_at FROM invoices
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.InvoiceID,
			&i.InvoiceNumber,
			&i.UserInvoiceID,
			&i.UserInvoiceUsername,
			&i.InvoiceData,
			&i.InvoicePdf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
