// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type C2bTransaction struct {
	ID                int64     `json:"id"`
	Fullname          string    `json:"fullname"`
	Phone             string    `json:"phone"`
	Amount            int64     `json:"amount"`
	TransactionID     string    `json:"transaction_id"`
	OrgAccountBalance int64     `json:"org_account_balance"`
	TransactionTime   time.Time `json:"transaction_time"`
	CreatedAt         time.Time `json:"created_at"`
}

type Entry struct {
	EntryID       int64     `json:"entry_id"`
	ProductID     int32     `json:"product_id"`
	ProductName   string    `json:"product_name"`
	ProductPrice  int32     `json:"product_price"`
	QuantityAdded int32     `json:"quantity_added"`
	CreatedAt     time.Time `json:"created_at"`
}

type Invoice struct {
	InvoiceID           int64     `json:"invoice_id"`
	InvoiceNumber       string    `json:"invoice_number"`
	UserInvoiceID       int32     `json:"user_invoice_id"`
	UserInvoiceUsername string    `json:"user_invoice_username"`
	InvoiceData         []byte    `json:"invoice_data"`
	InvoicePdf          []byte    `json:"invoice_pdf"`
	CreatedAt           time.Time `json:"created_at"`
	InvoiceDate         time.Time `json:"invoice_date"`
}

type Product struct {
	ProductID   int64     `json:"product_id"`
	ProductName string    `json:"product_name"`
	UnitPrice   int32     `json:"unit_price"`
	Packsize    string    `json:"packsize"`
	CreatedAt   time.Time `json:"created_at"`
}

type PurchaseOrder struct {
	ID              string    `json:"id"`
	SupplierName    string    `json:"supplier_name"`
	SupplierAddress string    `json:"supplier_address"`
	LpoData         []byte    `json:"lpo_data"`
	LpoPdf          []byte    `json:"lpo_pdf"`
	CreatedAt       time.Time `json:"created_at"`
}

type Receipt struct {
	ReceiptID           int64     `json:"receipt_id"`
	ReceiptNumber       string    `json:"receipt_number"`
	UserReceiptID       int32     `json:"user_receipt_id"`
	UserReceiptUsername string    `json:"user_receipt_username"`
	ReceiptData         []byte    `json:"receipt_data"`
	ReceiptPdf          []byte    `json:"receipt_pdf"`
	CreatedAt           time.Time `json:"created_at"`
	PaymentMethod       string    `json:"payment_method"`
}

type StockValue struct {
	UserID int32 `json:"user_id"`
	Value  int64 `json:"value"`
}

type Transaction struct {
	TransactionID      string    `json:"transaction_id"`
	TransactionUserID  int32     `json:"transaction_user_id"`
	Amount             int32     `json:"amount"`
	Status             bool      `json:"status"`
	DataSold           []byte    `json:"data_sold"`
	PhoneNumber        string    `json:"phone_number"`
	MpesaReceiptNumber string    `json:"mpesa_receipt_number"`
	ResultDescription  string    `json:"result_description"`
	CreatedAt          time.Time `json:"created_at"`
	PaymentMethod      string    `json:"payment_method"`
}

type User struct {
	UserID      int64     `json:"user_id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Email       string    `json:"email"`
	PhoneNumber string    `json:"phone_number"`
	Address     string    `json:"address"`
	Stock       []byte    `json:"stock"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}
