// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: receipts.sql

package db

import (
	"context"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts(
    receipt_number, user_receipt_id, receipt_data, user_receipt_username, receipt_pdf
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING receipt_id, receipt_number, user_receipt_id, user_receipt_username, receipt_data, receipt_pdf, created_at
`

type CreateReceiptParams struct {
	ReceiptNumber       string `json:"receipt_number"`
	UserReceiptID       int32  `json:"user_receipt_id"`
	ReceiptData         []byte `json:"receipt_data"`
	UserReceiptUsername string `json:"user_receipt_username"`
	ReceiptPdf          []byte `json:"receipt_pdf"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt,
		arg.ReceiptNumber,
		arg.UserReceiptID,
		arg.ReceiptData,
		arg.UserReceiptUsername,
		arg.ReceiptPdf,
	)
	var i Receipt
	err := row.Scan(
		&i.ReceiptID,
		&i.ReceiptNumber,
		&i.UserReceiptID,
		&i.UserReceiptUsername,
		&i.ReceiptData,
		&i.ReceiptPdf,
		&i.CreatedAt,
	)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT receipt_id, receipt_number, user_receipt_id, user_receipt_username, receipt_data, receipt_pdf, created_at FROM receipts
WHERE receipt_number = $1 
LIMIT 1
`

func (q *Queries) GetReceipt(ctx context.Context, receiptNumber string) (Receipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, receiptNumber)
	var i Receipt
	err := row.Scan(
		&i.ReceiptID,
		&i.ReceiptNumber,
		&i.UserReceiptID,
		&i.UserReceiptUsername,
		&i.ReceiptData,
		&i.ReceiptPdf,
		&i.CreatedAt,
	)
	return i, err
}

const getReceiptByID = `-- name: GetReceiptByID :one
SELECT receipt_id, receipt_number, user_receipt_id, user_receipt_username, receipt_data, receipt_pdf, created_at FROM receipts
WHERE receipt_id = $1 
LIMIT 1
`

func (q *Queries) GetReceiptByID(ctx context.Context, receiptID int64) (Receipt, error) {
	row := q.db.QueryRow(ctx, getReceiptByID, receiptID)
	var i Receipt
	err := row.Scan(
		&i.ReceiptID,
		&i.ReceiptNumber,
		&i.UserReceiptID,
		&i.UserReceiptUsername,
		&i.ReceiptData,
		&i.ReceiptPdf,
		&i.CreatedAt,
	)
	return i, err
}

const getUserReceiptsByID = `-- name: GetUserReceiptsByID :many
SELECT receipt_id, receipt_number, user_receipt_id, user_receipt_username, receipt_data, receipt_pdf, created_at FROM receipts
WHERE user_receipt_id = $1
`

func (q *Queries) GetUserReceiptsByID(ctx context.Context, userReceiptID int32) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, getUserReceiptsByID, userReceiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ReceiptID,
			&i.ReceiptNumber,
			&i.UserReceiptID,
			&i.UserReceiptUsername,
			&i.ReceiptData,
			&i.ReceiptPdf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReceiptsByUsername = `-- name: GetUserReceiptsByUsername :many
SELECT receipt_id, receipt_number, user_receipt_id, user_receipt_username, receipt_data, receipt_pdf, created_at FROM receipts
WHERE user_receipt_username = $1
`

func (q *Queries) GetUserReceiptsByUsername(ctx context.Context, userReceiptUsername string) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, getUserReceiptsByUsername, userReceiptUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ReceiptID,
			&i.ReceiptNumber,
			&i.UserReceiptID,
			&i.UserReceiptUsername,
			&i.ReceiptData,
			&i.ReceiptPdf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceipts = `-- name: ListReceipts :many
SELECT receipt_id, receipt_number, user_receipt_id, user_receipt_username, receipt_data, receipt_pdf, created_at FROM receipts
ORDER BY receipt_id
`

func (q *Queries) ListReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, listReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ReceiptID,
			&i.ReceiptNumber,
			&i.UserReceiptID,
			&i.UserReceiptUsername,
			&i.ReceiptData,
			&i.ReceiptPdf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
